### ISSUE TITLE
Harvesting fails with missing python attribute

### ISSUE THREAD

**Issue by cwmeijer** [research-software-directory/research-software-directory#433] opened 2020-10-05 08:21 UTC
When running any harvesting jobs, I'm getting errors in the python code. Looks like some version problem of some dependencies:

```Powershell
PS C:\Users\ChristiaanMeijer\Documents\research-software-directory> docker-compose exec harvesting python app.py harvest all
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from zotero import get_mentions
  File "/app/zotero.py", line 10, in <module>
    from pyzotero import zotero
  File "/usr/local/lib/python3.6/site-packages/pyzotero/zotero.py", line 102, in <module>
    feedparser._FeedParserMixin._isBase64 = ib64_patched
AttributeError: module 'feedparser' has no attribute '_FeedParserMixin'
```
I get the same error in the harvesting job that automatically runs every 10 minutes:
```Powershell
rsd-harvesting   | Traceback (most recent call last):
rsd-harvesting   |   File "app.py", line 8, in <module>
rsd-harvesting   |     from zotero import get_mentions
rsd-harvesting   |   File "/app/zotero.py", line 10, in <module>
rsd-harvesting   |     from pyzotero import zotero
rsd-harvesting   |   File "/usr/local/lib/python3.6/site-packages/pyzotero/zotero.py", line 102, in <module>
rsd-harvesting   |     feedparser._FeedParserMixin._isBase64 = ib64_patched
rsd-harvesting   | AttributeError: module 'feedparser' has no attribute '_FeedParserMixin'
```

**Comment by fdiblen** [comment] 2020-10-05 08:25
I can confirm that I have the same issue. My system information is below.
- Which operating system you're running
OS: Arch Linux
Kernel: 5.8.12-arch1-1 #1 SMP PREEMPT Sat, 26 Sep 2020 21:42:58 +0000 x86_64 GNU/Linux
- Which version of the software you're running
Fresh clone - master branch (6b84880)
- Any logging or error output you see
No other logs

**Comment by sverhoeven** [comment] 2020-10-05 09:17
Do not get error when I run 

```
docker-compose exec harvesting python app.py harvest mentions
2020-10-05 09:15:12,079 zotero [INFO] Database collection 'mention' is currently at version 6118; Zotero library 1689348 is currently at version 6118.
2020-10-05 09:15:12,571 zotero [INFO] Found 0 new or updated items in Zotero library 1689348 since version 6118.
```

<details><summary>Pip list</summary>

```
docker-compose exec harvesting pip3 list
Package         Version   
--------------- ----------
beautifulsoup4  4.6.0     
bibtexparser    1.1.0     
certifi         2020.4.5.1
cffconvert      1.3.3     
chardet         3.0.4     
click           6.7       
dateutils       0.6.6     
docopt          0.6.2     
feedparser      5.2.1     
future          0.18.2    
idna            2.7       
pathlib         1.0.1     
pip             19.1.1    
PyJWT           1.5.3     
pykwalify       1.7.0     
pymongo         3.6.1     
pyparsing       2.4.7     
python-dateutil 2.6.1     
pytz            2019.3    
PyYAML          5.3.1     
Pyzotero        1.3.1     
requests        2.20.0    
ruamel.yaml     0.15.100  
setuptools      41.0.1    
six             1.14.0    
urllib3         1.24.3    
wheel           0.33.3  
```
</details>

**Comment by sverhoeven** [comment] 2020-10-05 09:46
Rebuilding images and running harverster now give same AttributeError. 

As reported https://github.com/urschrei/pyzotero/issues/117 we should update pyzotero to at least 1.4.18

**Comment by jspaaks** [comment] 2020-10-06 16:55
can we close this?

**Comment by sverhoeven** [comment] 2020-10-07 07:39
Yes, just tested fix by @fdiblen and it works for me now.

**Comment by cwmeijer** [comment] 2020-10-07 08:27
works for me too. please close

**Closed** 2020-10-07 08:50 UTC
Labels: bug, standup
