### ISSUE TITLE
Certificate problem and warning when running on localhost

### ISSUE THREAD

**Issue by cwmeijer** [research-software-directory/research-software-directory#432] opened 2020-10-05 08:14 UTC
When running on localhost, I get the following in the logs:
```
An unexpected error occurred:
rsd-nginx-ssl    | The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "localhost": Domain name needs at least one dot
```
**It looks to me that the validation on the domain name is too strict and should allow localhost. Alternatively, if this is not really a problem, then we should note this in installation instructions in the readme.**

For some context, here's some more of the log:
```
rsd-nginx-ssl    | No SSL certificate found.
rsd-nginx-ssl    | Generating self-signed certificate
rsd-nginx-ssl    | + openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj '/CN=*/O=RSD./C=NL' -keyout /cert/privkey.pem -out /cert/fullchain.pem
rsd-nginx-ssl    | Generating a RSA private key
rsd-nginx-ssl    | ................................+++++
rsd-nginx-ssl    | ............................................................+++++
rsd-nginx-ssl    | writing new private key to '/cert/privkey.pem'
rsd-nginx-ssl    | -----
rsd-nginx-ssl    | crond: crond (busybox 1.31.1) started, log level 8
rsd-nginx-ssl    | ls: /etc/letsencrypt/live: No such file or directory
rsd-nginx-ssl    | + certbot certonly --webroot -w /acme -n --agree-tos --email cwmeijer@protonmail.com -d localhost --expand
rsd-nginx-ssl    | Saving debug log to /var/log/letsencrypt/letsencrypt.log
rsd-nginx-ssl    | Plugins selected: Authenticator webroot, Installer None
rsd-nginx-ssl    | Obtaining a new certificate
rsd-nginx-ssl    | An unexpected error occurred:
rsd-nginx-ssl    | The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "localhost": Domain name needs at least one dot
rsd-nginx-ssl    | IMPORTANT NOTES:
rsd-nginx-ssl    |  - Your account credentials have been saved in your Certbot
rsd-nginx-ssl    |    configuration directory at /etc/letsencrypt. You should make a
rsd-nginx-ssl    |    secure backup of this folder now. This configuration directory will
rsd-nginx-ssl    |    also contain certificates and private keys obtained by Certbot so
rsd-nginx-ssl    | Please see the logfiles in /var/log/letsencrypt for more details.
rsd-nginx-ssl    |    making regular backups of this folder is ideal.
rsd-nginx-ssl    | WARNING: Certbot failed to create certificate
```

More context: Running on Windows 10.

**Comment by fdiblen** [comment] 2020-10-05 08:27
This is probably due to the values in .env file. Emails and the domain names should be correct.
Maybe you can try:
email: test@test.com
domain: www.test.com

**Comment by cwmeijer** [comment] 2020-10-06 10:00
I'm using the default: 'localhost' 
It is of course a bit of an outlier, but it is the RSD's default, so it should not fail.

**Comment by jspaaks** [comment] 2020-10-06 16:38
Just FYI before peeps fall down a rabbit hole: the security error is known and has always been there for localhost. I agree it's not what you'd want, ideally.

**Comment by fdiblen** [comment] 2020-10-15 12:53
Closing as this is a duplicate of #418

**Closed by fdiblen** 2020-10-15 12:53 UTC
Labels: bug
