### ISSUE TITLE
Product pages fail to generate if contributors affiliation is not specified

### ISSUE THREAD

**Issue by jmaassen** [research-software-directory/research-software-directory#157] opened 2018-09-24 12:48 UTC
When setting up a demo RSD for the PROCESS project I forgot to specify the affiliation of the (only) contributor to a piece of software. 

The result was that the product page for that software failed to generate. It gave me a internal server error instead. The console of the docker-compose prints the following:

frontend_1   | [2018-09-24 12:40:14,470] ERROR in app: Exception on /software/medicalimaging [GET]
frontend_1   | Traceback (most recent call last):
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
frontend_1   |     response = self.full_dispatch_request()
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
frontend_1   |     rv = self.handle_user_exception(e)
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
frontend_1   |     reraise(exc_type, exc_value, tb)
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
frontend_1   |     raise value
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
frontend_1   |     rv = self.dispatch_request()
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
nginx_1      | 172.18.0.2 - - [24/Sep/2018:12:40:14 +0000] "GET /software/medicalimaging HTTP/1.0" 500 291 "https://localhost/?aax\x5Cs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36" "172.18.0.1"
nginx_ssl_1  | 172.18.0.1 - - [24/Sep/2018:12:40:14 +0000] "GET /software/medicalimaging HTTP/1.1" 500 291 "https://localhost/?aax\x5Cs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36" "-"
frontend_1   |     return self.view_functions[rule.endpoint](**req.view_args)
frontend_1   |   File "/src/app/application.py", line 136, in software_product_page_template
frontend_1   |     mention_types=mention_types,
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
frontend_1   |     context, ctx.app)
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
frontend_1   |     rv = template.render(context)
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
frontend_1   |     return original_render(self, *args, **kwargs)
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
frontend_1   |     return self.environment.handle_exception(exc_info, True)
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
frontend_1   |     reraise(exc_type, exc_value, tb)
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
frontend_1   |     raise value.with_traceback(tb)
frontend_1   |   File "/src/app/../templates/software/software_template.html", line 1, in top-level template code
frontend_1   |     {% extends "layout_template.html" %}
frontend_1   |   File "/src/app/../templates/layout_template.html", line 69, in top-level template code
frontend_1   |     {%- block content -%}{%- endblock -%}
frontend_1   |   File "/src/app/../templates/software/software_template.html", line 33, in block "content"
frontend_1   |     {% include 'software/contributors.html' %}
frontend_1   |   File "/src/app/../templates/software/contributors.html", line 60, in top-level template code
frontend_1   |     {{contactPerson.affiliations[0].foreignKey.name}}
frontend_1   |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
frontend_1   |     return getattr(obj, attribute)
frontend_1   | jinja2.exceptions.UndefinedError: list object has no element 0

**Comment by jmaassen** [comment] 2018-09-24 12:49
I guess the admin page should either have a contributor affiliation as a mandatory field, or be able to handle it being empty.

**Comment by jspaaks** [comment] 2019-03-12 15:20
Turns out the ``contributors`` were safeguarded already, but your case must have been caused by the ``contactPerson``, which wasn't safeguarded yet (fixed by d69ff698d1b39a6606615303bf644a73d46f94db).

**Closed** 2019-03-12 15:36 UTC
